"""Privacy-safe Markdown support report for issues and community troubleshooting."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

import typer

from devdoctor import __version__
from devdoctor.hardening import safe_diagnostic_snapshot

_REGISTERED_APP_IDS: set[int] = set()


def _display(value: Any) -> str:
    if value is None or value == "":
        return "unknown"
    rendered = str(value).replace("`", "'").replace("\n", " ").replace("\r", " ")
    return rendered.replace("|", r"\|")


def render_support_markdown(snapshot: Mapping[str, Any]) -> str:
    """Render a bounded Markdown report from an already scrubbed diagnostic snapshot."""

    platform = snapshot.get("platform", {})
    package_managers = snapshot.get("package_managers", ())
    conflicts = snapshot.get("manager_conflicts", ())
    path = snapshot.get("path", {})

    lines = [
        "# DevDoctor support report",
        "",
        f"Generated by DevDoctor `{__version__}`.",
        "",
        "> This report is generated from DevDoctor's privacy-scrubbed diagnostics.",
        "> It intentionally omits hostname, username, raw PATH values, arbitrary environment",
        "> values, shell history, and credentials.",
        "",
        "## Platform",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    if isinstance(platform, Mapping):
        for key in (
            "distribution",
            "distribution_id",
            "variant_id",
            "architecture",
            "kernel",
            "python",
            "session_type",
            "shell",
            "atomic_host",
        ):
            lines.append(f"| `{key}` | `{_display(platform.get(key))}` |")

    lines.extend(
        [
            "",
            "## Package managers",
            "",
            "| Manager | Installed | Version | Path class | Family |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    if isinstance(package_managers, (list, tuple)) and package_managers:
        for manager in package_managers:
            if not isinstance(manager, Mapping):
                continue
            lines.append(
                "| "
                f"`{_display(manager.get('id'))}` | "
                f"`{_display(manager.get('installed'))}` | "
                f"`{_display(manager.get('version'))}` | "
                f"`{_display(manager.get('path_class'))}` | "
                f"`{_display(manager.get('family'))}` |"
            )
    else:
        lines.append("| _none detected_ |  |  |  |  |")

    lines.extend(["", "## Package-manager conflicts", ""])
    if isinstance(conflicts, (list, tuple)) and conflicts:
        for conflict in conflicts:
            if not isinstance(conflict, Mapping):
                continue
            managers = conflict.get("managers", ())
            if isinstance(managers, (list, tuple)):
                manager_text = ", ".join(str(item) for item in managers)
            else:
                manager_text = "unknown"
            lines.append(
                f"- **{_display(conflict.get('severity'))} / "
                f"{_display(conflict.get('kind'))}** "
                f"(`{_display(manager_text)}`): {_display(conflict.get('message'))}"
            )
    else:
        lines.append("No package-manager conflicts detected.")

    lines.extend(["", "## PATH summary", ""])
    if isinstance(path, Mapping):
        lines.append(f"- Entry count: `{_display(path.get('entry_count'))}`")
        lines.append(
            f"- Contains empty PATH entry: `{_display(path.get('contains_empty_entry'))}`"
        )

    lines.extend(
        [
            "",
            "## Reproduction",
            "",
            "Add the failing DevDoctor command and the smallest relevant error output here.",
            "Do not paste secrets, tokens, private repository contents, or unrelated env data.",
            "",
        ]
    )
    return "\n".join(lines)


def register_support_report_command(app: typer.Typer) -> None:
    """Register a copy/paste-ready support report command once."""

    if id(app) in _REGISTERED_APP_IDS:
        return
    _REGISTERED_APP_IDS.add(id(app))

    @app.command("support")
    def support(
        output: Path = typer.Option(
            Path("devdoctor-support.md"),
            "--output",
            "-o",
            help="Markdown destination when --stdout is not used.",
        ),
        stdout: bool = typer.Option(False, "--stdout", help="Print Markdown to stdout."),
    ) -> None:
        """Create a privacy-safe Markdown report suitable for a GitHub issue."""

        payload = render_support_markdown(safe_diagnostic_snapshot())
        if stdout:
            typer.echo(payload, nl=False)
            return
        output.write_text(payload, encoding="utf-8")
        typer.echo(str(output))
